"use client";
import { useEffect, useMemo, useState } from "react";
type Customer={id:string;name:string;phone:string;total:number;completed:number;noShows:number;cancelled:number;lastAppointment:string|null;nextAppointment:string|null;lastService:string|null};
const when=(v:string|null)=>v?new Date(v).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}):"Nenhum";
export default function Customers(){
 const[items,setItems]=useState<Customer[]>([]),[name,setName]=useState(""),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/staff/customers",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"Não foi possível carregar.");setItems(j.customers||[]);setName(j.profile?.name||"")}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase().replace(/\D/g,"");const raw=query.trim().toLowerCase();return items.filter(i=>i.name.toLowerCase().includes(raw)||i.phone.includes(q))},[items,query]);
 return <main className="min-h-screen bg-[#080909] p-4 text-[#f4f1e8] sm:p-8"><div className="mx-auto max-w-5xl">
  <header className="mb-7 flex items-center justify-between gap-4"><div><a href="/operacao" className="text-xl font-black tracking-[.16em]"><span className="text-[#d6ae42]">B.</span> ALMEIDA</a><p className="mt-2 text-xs text-[#777]">Meus clientes · {name||"carregando"}</p></div><a href="/operacao" className="rounded-lg border border-[#5e502a] p-3 text-xs font-black text-[#d6ae42]">VOLTAR</a></header>
  <p className="text-[10px] font-bold tracking-[.2em] text-[#d6ae42]">RELACIONAMENTO</p><h1 className="mt-1 text-3xl font-black">Meus clientes</h1><p className="mt-2 text-sm text-[#777]">Cada profissional vê apenas os próprios clientes.</p>
  <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar nome ou telefone" aria-label="Pesquisar cliente" className="my-6 w-full rounded-xl border border-[#343734] bg-[#151716] p-4 text-white placeholder:text-[#666]"/>
  {error?<p className="rounded-lg border border-red-900 bg-red-950/30 p-4 text-red-300">{error}</p>:loading?<p className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-10 text-center text-[#777]">Carregando clientes...</p>:visible.length===0?<p className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-10 text-center text-[#777]">Nenhum cliente encontrado.</p>:<section className="grid gap-3 sm:grid-cols-2">{visible.map(c=><article key={c.id} className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black">{c.name}</h2><a href={`tel:${c.phone}`} className="mt-1 block text-sm text-[#d6ae42]">{c.phone}</a></div><span className="rounded-full border border-[#5d502a] px-3 py-1 text-xs text-[#d6ae42]">{c.completed} concluído{c.completed===1?"":"s"}</span></div><dl className="mt-5 grid gap-3 text-sm"><div><dt className="text-[#777]">Próximo agendamento</dt><dd className="mt-1 font-bold">{when(c.nextAppointment)}</dd></div><div><dt className="text-[#777]">Último atendimento</dt><dd className="mt-1">{when(c.lastAppointment)}{c.lastService?` · ${c.lastService}`:""}</dd></div><div className="grid grid-cols-3 gap-2 border-t border-[#292b29] pt-3 text-center"><div><b>{c.total}</b><small className="block text-[#777]">marcações</small></div><div><b>{c.noShows}</b><small className="block text-[#777]">ausências</small></div><div><b>{c.cancelled}</b><small className="block text-[#777]">cancelados</small></div></div></dl></article>)}</section>}
 </div></main>
}
