"use client";
import {useEffect,useState} from "react";
import StaffNav from "../components/StaffNav";

type Row={name:string;count:number;grossCents:number;ownerCents:number;barberCents:number};
type Payment={method:string;name:string;count:number;totalCents:number};
type Data={profile:{name:string;role:"owner"|"barber"};periodDays:number;summary:{grossCents:number;completed:number;cancelled:number;ticketCents:number;myCents:number;repasseCents:number;sinvasCompleted:number;sinvasGrossCents:number;sinvasRepasseCents:number;sinvasAmountCents:number};services:Row[];barbers:Row[];payments:Payment[]};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
const csvMoney=(v:number)=>(v/100).toFixed(2).replace(".",",");

export default function Reports(){
 const[days,setDays]=useState(30),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{setLoading(true);setError("");fetch(`/api/staff/reports?days=${days}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[days]);
 function download(){if(!data)return;const rows=[
  ["Relatório","Barbearia Almeida"],["Perfil",data.profile.name],["Período",`${data.periodDays} dias`],[""],
  ["Resumo","Quantidade","Valor (R$)"],["Atendimentos concluídos",data.summary.completed,csvMoney(data.summary.grossCents)],["Cancelados ou ausentes",data.summary.cancelled,""],["Ticket médio","",csvMoney(data.summary.ticketCents)],[data.profile.role==="owner"?"Receita do Lucas":"Parte do Sinvas (60%)","",csvMoney(data.summary.myCents)],[data.profile.role==="owner"?"Repasse a receber do Sinvas":"Repasse ao Lucas (40%)","",csvMoney(data.summary.repasseCents)],...(data.profile.role==="owner"?[["Atendimentos concluídos pelo Sinvas",data.summary.sinvasCompleted,csvMoney(data.summary.sinvasGrossCents)],["Parte do Sinvas (60%)","",csvMoney(data.summary.sinvasAmountCents)],["Repasse do Lucas sobre Sinvas (40%)","",csvMoney(data.summary.sinvasRepasseCents)]]:[]),[""],
  ["Forma de pagamento","Quantidade","Valor (R$)"],...data.payments.map(p=>[p.name,p.count,csvMoney(p.totalCents)]),[""],
  ["Serviço","Quantidade","Faturamento (R$)"],...data.services.map(s=>[s.name,s.count,csvMoney(s.grossCents)]),[""],
  ["Profissional","Atendimentos","Produção (R$)"],...data.barbers.map(b=>[b.name,b.count,csvMoney(b.grossCents)])
 ];const csv="\uFEFF"+rows.map(row=>row.map(cell=>`"${String(cell??"").replaceAll('"','""')}"`).join(";")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`relatorio-${data.profile.name.toLowerCase().replaceAll(" ","-")}-${data.periodDays}-dias.csv`;a.click();URL.revokeObjectURL(url)}
 if(error&&!data&&!loading)return <main className="min-h-screen bg-[#080909] p-5 text-[#f4f1e8] grid place-items-center"><section className="w-full max-w-md rounded-2xl border border-[#3f3825] bg-[#151716] p-8 text-center"><div className="text-4xl">🔒</div><h1 className="mt-4 text-2xl font-black">Relatório protegido</h1><p className="mt-3 text-sm text-[#888]">{error}</p><a href="/login" className="mt-6 block rounded-lg bg-[#d6ae42] p-4 font-black text-black">ENTRAR COM CONTA AUTORIZADA</a></section></main>;
 return <main className="report-print min-h-screen bg-[#080909] p-4 pb-32 text-[#f4f1e8] sm:p-8 sm:pb-32"><div className="mx-auto max-w-6xl">
  <header className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><a href="/operacao" className="text-xl font-black tracking-[.16em]"><span className="text-[#d6ae42]">B.</span> ALMEIDA</a><p className="mt-2 text-xs text-[#777]">Relatório real · {data?.profile.name||"carregando"}</p></div><div className="print-hidden flex flex-wrap gap-2">{[[7,"7 dias"],[30,"30 dias"],[365,"Este ano"]].map(([n,label])=><button key={n} onClick={()=>setDays(Number(n))} className={`rounded-lg px-4 py-3 text-xs font-black ${days===n?"bg-[#d6ae42] text-black":"border border-[#2a2d2a] text-[#888]"}`}>{label}</button>)}<button onClick={download} disabled={!data||loading} className="rounded-lg border border-[#d6ae42] px-4 py-3 text-xs font-black text-[#d6ae42] disabled:opacity-40">BAIXAR CSV</button><button onClick={()=>window.print()} disabled={!data||loading} className="rounded-lg bg-[#d6ae42] px-4 py-3 text-xs font-black text-black disabled:opacity-40">IMPRIMIR / PDF</button></div></header>
  <div className="mb-6"><p className="text-[10px] font-bold tracking-[.2em] text-[#d6ae42]">DADOS DO BANCO</p><h1 className="mt-1 text-3xl font-black">{data?.profile.role==="owner"?"Relatório da barbearia":"Meu relatório"}</h1><p className="mt-2 text-sm text-[#777]">{data?.profile.role==="owner"?"Lucas visualiza o resultado completo.":"Seus dados estão separados do financeiro do Lucas."}</p></div>
	  {error&&<p className="mb-4 rounded-lg border border-red-900 bg-red-950/30 p-4 text-sm text-red-300">{error}</p>}
	  {!loading&&data?.profile.role==="owner"&&<OwnerSinvas data={data}/>}
	  {loading?<p className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-10 text-center text-[#777]">Calculando relatório...</p>:data&&<><div className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><Card label="Faturamento" value={money(data.summary.grossCents)} note="Atendimentos concluídos"/><Card label="Atendimentos" value={String(data.summary.completed)} note="Somente concluídos"/><Card label="Ticket médio" value={money(data.summary.ticketCents)} note="Por atendimento"/><Card label="Cancelados/ausentes" value={String(data.summary.cancelled)} note="No período selecionado"/></div><div className="mb-5 grid gap-3 sm:grid-cols-3">{data.payments.map(p=><Card key={p.method} label={p.name} value={money(p.totalCents)} note={`${p.count} pagamento${p.count===1?"":"s"}`}/>)}</div><div className="grid gap-5 lg:grid-cols-[1.3fr_1fr]"><section className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-5"><h2 className="mb-5 font-black">Serviços realizados</h2>{data.services.length===0?<p className="text-sm text-[#777]">Nenhum serviço concluído no período.</p>:data.services.map((s,index)=><div key={s.name} className="mb-5 last:mb-0"><div className="mb-2 flex items-center justify-between text-sm"><div><b>{s.name}</b><small className="ml-2 text-[#777]">{s.count}x</small></div><strong className="text-[#d6ae42]">{money(s.grossCents)}</strong></div><div className="h-2 overflow-hidden rounded-full bg-[#262826]"><span className="block h-full rounded-full bg-[#d6ae42]" style={{width:`${Math.max(8,100-index*18)}%`}}/></div></div>)}</section><section className="grid gap-4"><div className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-5"><h2 className="mb-5 font-black">{data.profile.role==="owner"?"Desempenho por barbeiro":"Minha produção"}</h2>{data.barbers.map(b=><div key={b.name} className="mb-4 flex items-center justify-between border-b border-[#292b29] pb-4 last:border-0"><div><b>{b.name}</b><small className="block text-[#777]">{b.count} atendimentos</small></div><strong>{money(b.grossCents)}</strong></div>)}</div><div className="rounded-xl border border-[#5a4c27] bg-[#1d1a11] p-5"><small className="text-[#9a8a5a]">{data.profile.role==="owner"?"RECEITA DO LUCAS":"MINHA PARTE · 60%"}</small><strong className="my-3 block text-3xl text-[#d6ae42]">{money(data.summary.myCents)}</strong><p className="text-xs text-[#777]">Calculado somente sobre atendimentos concluídos.</p></div><div className="rounded-xl border border-[#5a4c27] bg-[#1d1a11] p-5"><small className="text-[#9a8a5a]">{data.profile.role==="owner"?"REPASSE A RECEBER DO SINVAS":"REPASSE AO LUCAS · 40%"}</small><strong className="my-3 block text-3xl text-[#d6ae42]">{money(data.summary.repasseCents)}</strong></div></section></div></>}
 </div><StaffNav active="relatorio"/></main>
}
function Card({label,value,note}:{label:string;value:string;note:string}){return <article className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-5"><small className="text-[9px] font-bold tracking-wider text-[#888]">{label.toUpperCase()}</small><b className="my-3 block text-2xl text-[#d6ae42]">{value}</b><span className="text-xs text-[#777]">{note}</span></article>}

function OwnerSinvas({data}:{data:Data}){return <section className="mb-5 rounded-xl border border-[#5a4c27] bg-[#17150f] p-5"><div className="mb-4"><p className="text-[10px] font-bold tracking-[.2em] text-[#d6ae42]">PRODUÇÃO DO SINVAS</p><h2 className="mt-1 text-xl font-black">Resumo do período selecionado</h2></div><div className="grid gap-3 sm:grid-cols-3"><Card label="Cortes do Sinvas" value={String(data.summary.sinvasCompleted)} note="Atendimentos concluídos"/><Card label="Produção do Sinvas" value={money(data.summary.sinvasGrossCents)} note={`${money(data.summary.sinvasAmountCents)} para o Sinvas · 60%`}/><Card label="Repasse para Lucas" value={money(data.summary.sinvasRepasseCents)} note="40% da produção do Sinvas"/></div></section>}
