"use client";
import { useEffect, useMemo, useState } from "react";
import StaffNav from "../components/StaffNav";

type Status = "pending" | "confirmed" | "completed" | "cancelled" | "no_show";
type Item = { id:string; startsAt:string; endsAt:string; status:Status; priceCents:number; paymentMethod?:string|null; serviceName:string; customerName:string; customerPhone:string; barberName:string };
const labels:Record<Status,string>={pending:"Aguardando",confirmed:"Confirmado",completed:"Concluído",cancelled:"Cancelado",no_show:"Ausente"};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"});
const addDays=(value:string,days:number)=>{const d=new Date(`${value}T12:00:00`);d.setDate(d.getDate()+days);return d.toLocaleDateString("en-CA")};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v/100);
const when=(v:string)=>new Date(v).toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo",day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"});

export default function AppointmentsHistory(){
 const initial=today();
 const[from,setFrom]=useState(initial),[to,setTo]=useState(initial),[items,setItems]=useState<Item[]>([]),[name,setName]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/staff/history?from=${from}&to=${to}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Não foi possível carregar.");setItems(j.appointments||[]);setName(j.profile?.name||"")}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[from,to]);
 const setPeriod=(kind:"today"|"tomorrow"|"week")=>{const base=today();setFrom(kind==="tomorrow"?addDays(base,1):base);setTo(kind==="week"?addDays(base,6):kind==="tomorrow"?addDays(base,1):base)};
 const counts=useMemo(()=>({active:items.filter(i=>["pending","confirmed"].includes(i.status)).length,completed:items.filter(i=>i.status==="completed").length,closed:items.filter(i=>["cancelled","no_show"].includes(i.status)).length}),[items]);
 return <main className="min-h-screen bg-[#080909] p-4 pb-32 text-[#f4f1e8] sm:p-8 sm:pb-32"><div className="mx-auto max-w-5xl">
  <header className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><a href="/operacao" className="text-xl font-black tracking-[.16em]"><span className="text-[#d6ae42]">B.</span> ALMEIDA</a><p className="mt-2 text-xs text-[#777]">Meus agendamentos · {name||"carregando"}</p></div><a href="/operacao" className="rounded-lg border border-[#5e502a] p-3 text-xs font-black text-[#d6ae42]">VOLTAR</a></header>
  <p className="text-[10px] font-bold tracking-[.2em] text-[#d6ae42]">HISTÓRICO E AGENDA</p><h1 className="mt-1 text-3xl font-black">Meus agendamentos</h1><p className="mt-2 text-sm text-[#777]">Consulte somente os seus horários por dia ou período.</p>
  <section className="my-6 rounded-xl border border-[#2a2d2a] bg-[#151716] p-4"><div className="grid grid-cols-3 gap-2"><button onClick={()=>setPeriod("today")} className="rounded-lg bg-[#d6ae42] p-3 text-xs font-black text-black">HOJE</button><button onClick={()=>setPeriod("tomorrow")} className="rounded-lg border border-[#5e502a] p-3 text-xs font-black text-[#d6ae42]">AMANHÃ</button><button onClick={()=>setPeriod("week")} className="rounded-lg border border-[#5e502a] p-3 text-xs font-black text-[#d6ae42]">7 DIAS</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Data inicial<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-2 block w-full rounded-lg border border-[#343734] bg-[#090a09] p-3 text-white"/></label><label className="text-sm">Data final<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)} className="mt-2 block w-full rounded-lg border border-[#343734] bg-[#090a09] p-3 text-white"/></label></div></section>
  <div className="mb-5 grid grid-cols-3 gap-3">{[["Agendados",counts.active],["Concluídos",counts.completed],["Ausentes/cancelados",counts.closed]].map(([label,value])=><article key={String(label)} className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-4"><small className="text-[9px] text-[#888]">{label}</small><b className="mt-2 block text-2xl text-[#d6ae42]">{value}</b></article>)}</div>
  {error?<p className="rounded-lg border border-red-900 bg-red-950/30 p-4 text-red-300">{error}</p>:loading?<p className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-10 text-center text-[#777]">Carregando...</p>:items.length===0?<p className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-10 text-center text-[#777]">Nenhum agendamento neste período.</p>:<section className="grid gap-3">{items.map(i=><article key={i.id} className="rounded-xl border border-[#2a2d2a] bg-[#151716] p-5"><div className="flex items-start justify-between gap-3"><div><b className="text-[#d6ae42]">{when(i.startsAt)}</b><h2 className="mt-2 text-lg font-black">{i.customerName}</h2><p className="mt-1 text-sm text-[#888]">{i.serviceName} · {money(i.priceCents)}</p><a href={`tel:${i.customerPhone}`} className="mt-2 inline-block text-sm text-[#d6ae42]">{i.customerPhone}</a></div><span className="rounded-full border border-[#5d502a] px-3 py-1 text-[9px] uppercase text-[#d6ae42]">{labels[i.status]}</span></div></article>)}</section>}
 </div><StaffNav active="agenda"/></main>
}
